config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/index' =>"users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
   get '/' => "posts#top"
   resources :users, only: [:show, :edit, :update]
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
     belongs_to :user
     validates :title, :body, {presence:true} 
     validates :title, {length: {maximum: 100}}
     validates :body, {length: {maximum: 300}}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
   validates :email,{uniqueness: true, presence:true}
   attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!,except:[:top]
    before_action :configure_permitted_parameters, if: :devise_controller?
    

    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post =Post.find(params[:id])
  end

  def index
    @posts =Post.all.order(created_at: :desc)
    @post =Post.new
  end

  def new
    @post =Post.new
  end

  def edit
    @post =Post.find(params[:id])
  end
  
  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post)
  end
  
  def create
    @post =Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to posts_path
  
  end
  
  def destroy
    @post =Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  
  
  
   private
    def post_params
      params.require(:post).permit(:title, :category, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users= User.all
  end
  
  def show
    @user =User.find(params[:id])
    @posts =@user.posts.reverse_order
  end
  
  def edit
    @user =User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  private 
def user_params
    params.require(:user).permit(:name, :profile_image)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
      <div id="slidemenu">
        <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
          <% if user_signed_in? %>
            <li class="">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
            <li class="">
              <%= link_to '新規投稿フォーム', new_post_path %>
            </li>
            <li>
              <%= link_to '投稿一覧', posts_path  %>
            </li>
            <li>
              <%= link_to 'ユーザー一覧', users_index_path %>
            </li>
            <li class="">
               <a href ="/users/<%= current_user.id %>">マイページ</a>
            </li>
          <% else %>
            <li class="">
              <%= link_to "新規登録", new_user_registration_path %>
            </li>
            <li class="" id="login-show">
              <%= link_to "ログイン", new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集画面</h1>
    <%= form_for(@post) do |f| %>
        <h4>タイトル</h4>
        <%= f.text_field :title %>
        <h4>本文</h4>
        <%= f.text_area :body %>
        <%= f.submit '保存' %>
    <% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<div class="post-box">
    <table class="table table-striped" id="row">
        <tr>
            <th class="col-sm-3">タイトル</th>
            <th class="col-sm-7">感想</th>
            <th class="col-sm-4"></th>
        </tr>
        <% @posts.each do |post| %>
        <tr>
            <td><%= post.title%></td>
            <td><%= post.body%></td>
            <td><%= link_to 'Show', post %></td>
        </tr>
        <% end %>
    </table>
</div>

<h1>新規投稿</h1>
<%=form_for(@post) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    
    <h4>感想</h4>
    <%= f.text_area :body %>
 
    <%= f.submit '投稿' %>
<% end %>

app/views/posts/new.html.erb
<div class="form-new">
    <h1>新規投稿</h1>
    <%=form_for(@post, url: posts_path) do |f| %>
     <% if @post.errors.any? %>
            <%= @post.errors.count %>件のエラーが発生しました
            <% @post.errors.full_messages.each do |message| %>
                <%= message %>
            <% end %>
    <% end %>
        <h4>タイトル</h4>
        <%= f.text_field :title %>
        
        <h4>感想</h4>
        <%= f.text_area :body  %>
     
        <%= f.submit '投稿' %>
    <% end %>
</div>

app/views/posts/show.html.erb
<h1>詳細ページ</h1>
<div class="post-box">
    <table class="table table-striped">
        <tr>
            <th>タイトル</th>
            <th>本文</th>
        </tr>
        <tr>
            <td><%= @post.title%></td>
            <td><%= @post.body%></td>
        </tr>
    </table>
</div>



<% if @post.user == current_user %>
    <%= link_to "編集", edit_post_path(@post)%>
    <%= link_to "削除", post_path(@post), method: :delete%>
<% end %>
<%= link_to "投稿一覧に戻る", posts_path(@post)%>

app/views/posts/top.html.erb
<div class="top">
    <div class="top-welcome">
        <h1>Moviesへようこそ！</h1>
        <p>Moviesでは、あなたが見た映画とその感想をシェアすることが出来ます。</p>
    </div>
    <div class="login-btn">
        <a href="/users/sign_up" class="btn btn-success active btn-lg">新規登録</a>
        <a href="/users/sign_in" class="btn btn-info active btn-lg">ログイン</a>
    </div>
</div>

app/views/users/edit.html.erb
<div class="body-wrap">
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">      
          <section class="slice slice-lg sct-color-1">
              <div class="container">
                  <div class="row">
                      <div class="col-md-4 col-md-offset-4">
                          <div class="form-user style-1 rounded has-shadow-1"> 
                            <div class="form-header text-center">
                                <h3 class="form-header-title">プロフィール編集</h3>
                            </div>
                            <div class="form-body">
                              <%= form_for(@user) do |f| %>
                                    <div class="form-group has-icon">
                                        <label class="control-label sr-only" for="inputEmail">Name</label>
                                        <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
                                        <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
                                    </div>
                                    
                                       
                                    <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                                <% end %>
                            </div>
                          </div> 
                      </div>
                  </div>
              </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
    <h1 class="users-heading">ユーザー一覧</h1>
    <table class="table table-striped">
        <tr>
            <th></th>
            <th></th>
        </tr>
        <% @users.each do |user| %>
            <tr>
                <td>
                    <a href ="/users/<%= user.id %>"><%= user.name %></a>
                </td>
            </tr>
 
        <% end %>
</div>

app/views/users/show.html.erb
<div class="profile-container">
    <section>  
        <h1 class="profile-name"><%= @user.name %></h1>
    
        <% if @user.id == current_user.id %>
        <p class="profile"><%= link_to "プロフィール編集", edit_user_path(@user), class: "pull-right" %></p>
        <% end %>
    </section>  
    <table class="table table-striped">
        <tr>
            <th>タイトル</th>
            <th>感想</th>
        </tr>
        <% @posts.each do |post| %>
        <tr>
            <td><%= post.title%></td>
            <td><%= post.body%></td>
            <td><%= link_to 'Show', post %></td>
        </tr>
        <% end %>
    </table>
</div>
    

</div>